export const modes = {
    NONE: "NONE",
    MONEY: "MONEY",
    TIME: "TIME",
    CONNECTIONS: "CONNECTIONS",
    INFORMATION: "INFORMATION",
    THINGS: "THINGS",
    SPACES: "SPACES"
};

export const planningModes = {
    PLANNED_VS_ACTUAL: "PLANNED_VS_ACTUAL",
    PLANNED_AND_PERCENT: "PLANNED_AND_PERCENT",
    ACTUAL_AND_PERCENT: "ACTUAL_AND_PERCENT"
};
